<?php
// Plugin definition
$plugin = array(
  'title' => t('TND Moscone Flipped'),
  'icon' => 'tnd-moscone-flipped.png',
  'category' => t('TND'),
  'theme' => 'tnd_moscone_flipped',
  'regions' => array(
    'header' => t('Header'),
    'intro' => t('Intro'),
    'sidebar' => t('Content Sidebar'),
    'contentmain' => t('Content'),
    'footer' => t('Footer'),
    'banner' => t('Banner'),
  ),
);
